- name: Create a temp dir
  tempfile:
    state: directory
    prefix: build
  register: temp_output

- name: Set tmp_path
  set_fact:
    tmp_path: "{{ temp_output.path }}"

- name: Template route.yml
  template:
    src: route.j2.yml
    dest: "{{ tmp_path }}/route.yml"

- name: Create the route
  command: oc create -f route.yml
  args:
    chdir: "{{ tmp_path }}"
  ignore_errors: yes
  changed_when: false

- name: Remove the temp directory
  file:
    path: "{{ tmp_path }}"
    state: absent