- name: Login as system:admin
  command: oc login -u system:admin
  changed_when: false

- name: Grant cluster-admin to developer
  command: 
  ignore_errors: true
  changed_when: false

- name: Log in as admin
  command: oc login -u admin -p admin -n default
  changed_when: false