- name: Login as system:admin 
  command: oc login -u system:admin

- name: Grant cluster-admin to developer 
  command: oc adm policy add-cluster-role-to-user cluster-admin developer

- name: Log in as developer
  command: oc login -u developer -p developer
 
- name: Set the namespace to 'default'
  command: oc project default 