- name: Create a temp dir
  tempfile:
    state: directory
    prefix: build
  register: temp_output

- name: Set tmp_path
  set_fact:
    tmp_path: "{{ temp_output.path }}"

- name: Clone nginx openshift router repository
  git:
    repo: 'https://github.com/nginxinc/nginx-openshift-router'
    dest: "{{ tmp_path }}/nginx-openshift-router"
    version: master
  ignore_errors: true

- name: Build NGINX docker image
  command: docker build -t nginx-openshift-router:0.2 .
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx"
  changed_when: false

- name: Get admin token
  command: oc whoami -t
  register: admintoken

- name: Get docker repository location
  command: minishift openshift registry
  register: dockerreg

- name: Logon to MiniShift private repository
  command: "docker login -p {{ admintoken.stdout }} -u unused {{ dockerreg.stdout }}"
  changed_when: false

- name: Tag NGINX docker image
  command: docker tag nginx-openshift-router:0.2 $(minishift openshift registry)/openshift/nginx-openshift-router:0.2
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx"
  changed_when: false

- name: Push NGINX docker image
  command: docker push $(minishift openshift registry)/openshift/nginx-openshift-router:0.2
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx"
  changed_when: false

- name: Backup default Router configuration
  command: "oc get -o yaml service/router dc/router clusterrolebinding/router-router-role serviceaccount/router"
  register: router
  changed_when: false

- name: Write default backup Router configuration to a file
  local_action:
    copy:
      content: "{{ router }}"
      dest: "$HOME/default-router-backup.yml"

- name: Delete Router
  command: "oc delete -f $HOME/default-router-backup.yml"
  changed_when: false

- name: Deploy NGINX router
  command: "oc adm router router --images={{ dockerreg.stdout }}/openshift/nginx-openshift-router:0.2 --type=''"
  changed_when: false

- name: Remove the temp directory
  file:
    path: "{{ tmp_path }}"
    state: absent