- name: Create a temp dir
  tempfile:
    state: directory
    prefix: build
  register: temp_output

- name: Set tmp_path
  set_fact:
    tmp_path: "{{ temp_output.path }}"

- name: Clone nginx openshift router repository
  git:
    repo: 'https://github.com/nginxinc/nginx-openshift-router'
    dest: "{{ tmp_path }}/nginx-openshift-router"
    version: master
  ignore_errors: true

- name: Copy NGINX license files to repository
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus/{{ item }}"
  with_items:
    - nginx-repo.crt
    - nginx-repo.key

- name: Build NGINX Plus docker image
  command: docker build -t nginx-plus-openshift-router:0.2 .
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus"
  changed_when: false

- name: Get admin token
  command: oc whoami -t
  register: admintoken

- name: Get docker repository location
  command: minishift openshift registry
  register: dockerreg

- name: Logon to MiniShift private repository
  shell: "set -o pipefail && true | eval $(minishift docker-env) && docker login -p {{ admintoken.stdout }} -u unused {{ dockerreg.stdout }}"
  args:
    executable: /bin/bash
  changed_when: false

- name: Tag NGINX Plus docker image
  command: "docker tag nginx-plus-openshift-router:0.2 {{ dockerreg.stdout }}/openshift/nginx-plus-openshift-router:0.2"
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus"
  changed_when: false

- name: Push NGINX Plus docker image
  command: "docker push {{ dockerreg.stdout }}/openshift/nginx-plus-openshift-router:0.2"
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus"
  changed_when: false

- name: Backup default Router configuration
  shell: "oc get -o yaml service/router dc/router clusterrolebinding/router-router-role serviceaccount/router > default-router-backup.yml"
  args:
    executable: /bin/bash
    chdir: $HOME

- name: Delete Router
  command: "oc delete -f $HOME/default-router-backup.yml"
  changed_when: false

- name: Deploy NGINX Plus router
  command: "oc adm router router --images={{ dockerreg.stdout }}/openshift/nginx-plus-openshift-router:0.2 --type=''"
  changed_when: false

- name: Remove the temp directory
  file:
    path: "{{ tmp_path }}"
    state: absent