- name: Login as system:admin
  command: "oc login -u system:admin -n default https://$(minishift ip):8443"
  changed_when: false

- name: Backup default Router configuration
  command: oc get -o yaml service/router dc/router clusterrolebinding/router-router-role serviceaccount/router > default-router-backup.yaml
  changed_when: false

- name: Delete Router
  command: oc delete -f default-router-backup.yaml
  changed_when: false

- name: Deploy NGINX Plus router
  command: oc adm router router --images=$(minishift openshift registry)/openshift/nginx-plus-openshift-router:0.2 --type=''
  when: nginx_plus
  changed_when: false

- name: Deploy NGINX router
  command: oc adm router router --images=$(minishift openshift registry)/openshift/nginx-openshift-router:0.2 --type=''
  when: not nginx_plus
  changed_when: false

- name: Log in as developer
  command: "oc login -u developer -p developer -n default https://$(minishift ip):8443"
  changed_when: false